import PDFDocument from 'pdfkit';
import type {
  TspiEdit,
  TspiModule,
  TspiViewer,
  TspiApproval,
  TspiSafetyAlert,
  TspiPlanRecord,
  TspiRedFlagScreen,
} from './types';
import { getApproval, getCaseCode } from './report';

type Doc = PDFKit.PDFDocument;

const COLORS = {
  blue: '#001FB8',
  orange: '#FF8442',
  text: '#0A0A0A',
  muted: '#4A5868',
  rule: '#D5DBE5',
  zebra: '#F3F5FA',
  noticeFill: '#FFF4EC',
  watermark: '#B0B0B0',
  white: '#FFFFFF',
};

const MM = 72 / 25.4;
const MARGIN = 18 * MM;
const HEADER_HEIGHT = 34;
const FOOTER_HEIGHT = 34;
const FONT = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const BODY_SIZE = 9.5;

export const PATIENT_CONTACT_URL = 'https://tspi-main.vercel.app/contact';
const FOOTER_TEXT =
  'Generated by TSPI Digital Twin from TSPI AI Brain output. Clinical decisions remain the responsibility of the treating physician.';

/**
 * The built-in PDF fonts only cover Windows-1252. Engine text carries a few Greek and math
 * symbols (μIU/mL, NF-κB, ≥); map those to readable equivalents rather than dropping them.
 */
const TRANSLITERATIONS: Record<string, string> = {
  μ: 'u',
  µ: 'u',
  κ: 'k',
  α: 'alpha',
  β: 'beta',
  γ: 'gamma',
  δ: 'delta',
  Δ: 'delta',
  '≥': '>=',
  '≤': '<=',
  '→': '->',
  '←': '<-',
  '↑': 'up',
  '↓': 'down',
  '≈': '~',
  '−': '-',
  ' ': ' ',
};
const WIN_ANSI_EXTRA = new Set('€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ');

export const toPdfText = (value: string): string => {
  let out = '';
  for (const char of value) {
    const mapped = TRANSLITERATIONS[char];
    if (mapped != null) {
      out += mapped;
      continue;
    }
    const code = char.codePointAt(0) ?? 0;
    const printable =
      char === '\n' ||
      (code >= 0x20 && code <= 0x7e) ||
      (code >= 0xa0 && code <= 0xff) ||
      WIN_ANSI_EXTRA.has(char);
    out += printable ? char : '?';
  }
  return out;
};

const txt = (value: string | number | boolean | null | undefined): string =>
  value == null || value === '' ? '-' : toPdfText(String(value));

const humanize = (value: string | null | undefined): string =>
  value
    ? value
        .replace(/_/g, ' ')
        .toLowerCase()
        .replace(/^\w/, (c) => c.toUpperCase())
    : '-';

const formatTimestamp = (value: string | null | undefined): string =>
  value ? value.replace('T', ' ').replace(/\.\d+/, '') : '-';

interface Column {
  header: string;
  width: number;
}

const contentWidth = (doc: Doc): number => doc.page.width - MARGIN * 2;
const bottomLimit = (doc: Doc): number => doc.page.height - MARGIN - FOOTER_HEIGHT;

const ensureSpace = (doc: Doc, height: number): void => {
  if (doc.y + height > bottomLimit(doc)) {
    doc.addPage();
  }
};

const drawHeaderBar = (doc: Doc, plan: TspiPlanRecord): void => {
  const { x, y } = { x: doc.x, y: doc.y };
  doc.save();
  doc.rect(0, 0, doc.page.width, HEADER_HEIGHT).fill(COLORS.blue);
  doc.fillColor(COLORS.white).font(FONT_BOLD).fontSize(11);
  doc.text('TSPI Digital Twin  ·  Treatment Plan', MARGIN, 12, { lineBreak: false });
  doc.font(FONT).fontSize(8.5);
  const right = toPdfText(`Case ${getCaseCode(plan)}   ·   Report ${plan.id}`);
  const rightWidth = doc.widthOfString(right);
  doc.text(right, doc.page.width - MARGIN - rightWidth, 13.5, { lineBreak: false });
  doc.restore();
  doc.x = x;
  doc.y = y;
};

const sectionTitle = (doc: Doc, title: string): void => {
  ensureSpace(doc, 48);
  doc.moveDown(0.8);
  doc.font(FONT_BOLD).fontSize(12).fillColor(COLORS.blue).text(title, MARGIN, doc.y);
  const lineY = doc.y + 2;
  doc
    .moveTo(MARGIN, lineY)
    .lineTo(MARGIN + contentWidth(doc), lineY)
    .lineWidth(1.2)
    .strokeColor(COLORS.orange)
    .stroke();
  doc.y = lineY + 6;
  doc.font(FONT).fontSize(BODY_SIZE).fillColor(COLORS.text);
};

const paragraph = (doc: Doc, text: string, color = COLORS.text): void => {
  doc.font(FONT).fontSize(BODY_SIZE).fillColor(color);
  doc.text(toPdfText(text), MARGIN, doc.y, { width: contentWidth(doc) });
};

const CELL_PAD = 4;

const rowHeight = (doc: Doc, cells: string[], columns: Column[], font: string): number => {
  doc.font(font).fontSize(BODY_SIZE - 1);
  return cells.reduce((max, cell, i) => {
    const h = doc.heightOfString(cell, { width: columns[i].width - CELL_PAD * 2 });
    return Math.max(max, h + CELL_PAD * 2);
  }, 0);
};

const drawRow = (
  doc: Doc,
  cells: string[],
  columns: Column[],
  options: { header?: boolean; zebra?: boolean },
): void => {
  const font = options.header ? FONT_BOLD : FONT;
  const height = rowHeight(doc, cells, columns, font);
  const top = doc.y;
  const width = columns.reduce((sum, c) => sum + c.width, 0);
  if (options.header || options.zebra) {
    doc.rect(MARGIN, top, width, height).fill(options.header ? COLORS.blue : COLORS.zebra);
  }
  doc
    .font(font)
    .fontSize(BODY_SIZE - 1)
    .fillColor(options.header ? COLORS.white : COLORS.text);
  let x = MARGIN;
  for (let i = 0; i < columns.length; i++) {
    doc.text(cells[i], x + CELL_PAD, top + CELL_PAD, { width: columns[i].width - CELL_PAD * 2 });
    x += columns[i].width;
  }
  doc
    .moveTo(MARGIN, top + height)
    .lineTo(MARGIN + width, top + height)
    .lineWidth(0.5)
    .strokeColor(COLORS.rule)
    .stroke();
  doc.y = top + height;
};

/** Widths are fractions of the content width. */
const table = (doc: Doc, spec: Array<[string, number]>, rows: string[][]): void => {
  const total = contentWidth(doc);
  const columns = spec.map(([header, fraction]) => ({ header, width: total * fraction }));
  const headerCells = columns.map((c) => c.header);
  const headerHeight = rowHeight(doc, headerCells, columns, FONT_BOLD);
  ensureSpace(doc, headerHeight + 20);
  drawRow(doc, headerCells, columns, { header: true });
  rows.forEach((raw, index) => {
    const cells = raw.map((cell) => txt(cell));
    const height = rowHeight(doc, cells, columns, FONT);
    if (doc.y + height > bottomLimit(doc)) {
      doc.addPage();
      drawRow(doc, headerCells, columns, { header: true });
    }
    drawRow(doc, cells, columns, { zebra: index % 2 === 1 });
  });
  doc.x = MARGIN;
  doc.font(FONT).fontSize(BODY_SIZE).fillColor(COLORS.text);
};

const keyValueTable = (doc: Doc, rows: Array<[string, string]>): void => {
  const total = contentWidth(doc);
  const columns: Column[] = [
    { header: '', width: total * 0.3 },
    { header: '', width: total * 0.7 },
  ];
  rows.forEach(([key, value], index) => {
    const cells = [txt(key), txt(value)];
    const height = rowHeight(doc, cells, columns, FONT);
    ensureSpace(doc, height);
    drawRow(doc, cells, columns, { zebra: index % 2 === 0 });
  });
  doc.x = MARGIN;
};

const noticeBox = (doc: Doc, lines: string[], accent: string): void => {
  const width = contentWidth(doc);
  const text = toPdfText(lines.join('\n'));
  doc.font(FONT_BOLD).fontSize(BODY_SIZE);
  const height = doc.heightOfString(text, { width: width - 20 }) + 14;
  ensureSpace(doc, height);
  const top = doc.y;
  doc.rect(MARGIN, top, width, height).fill(COLORS.noticeFill);
  doc.rect(MARGIN, top, 4, height).fill(accent);
  doc.fillColor(COLORS.text).text(text, MARGIN + 12, top + 7, { width: width - 20 });
  doc.y = top + height + 4;
  doc.x = MARGIN;
};

/** Renders one markdown line with **bold** runs; single-asterisk emphasis is dropped. */
const richLine = (doc: Doc, line: string, x: number, width: number, size: number): void => {
  const runs = toPdfText(line).split('**');
  const pieces = runs
    .map((run, i) => ({
      text: run.replace(/(^|[^*])\*(?!\s)([^*]+)\*/g, '$1$2'),
      bold: i % 2 === 1,
    }))
    .filter((piece) => piece.text.length > 0);
  if (!pieces.length) {
    return;
  }
  doc.fontSize(size).fillColor(COLORS.text);
  doc.x = x;
  pieces.forEach((piece, i) => {
    doc.font(piece.bold ? FONT_BOLD : FONT);
    const continued = i < pieces.length - 1;
    if (i === 0) {
      doc.text(piece.text, x, doc.y, { width, continued });
      return;
    }
    doc.text(piece.text, { continued });
  });
};

const markdown = (doc: Doc, source: string): void => {
  const width = contentWidth(doc);
  for (const rawLine of source.split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line.trim()) {
      doc.moveDown(0.35);
      continue;
    }
    const heading = /^(#{1,6})\s+(.*)$/.exec(line);
    if (heading) {
      ensureSpace(doc, 36);
      doc.moveDown(0.3);
      const level = heading[1].length;
      const title = heading[2].replace(/\*\*/g, '');
      doc
        .font(FONT_BOLD)
        .fontSize(level <= 2 ? 11.5 : 10.5)
        .fillColor(COLORS.blue)
        .text(toPdfText(title), MARGIN, doc.y, { width });
      doc.moveDown(0.15);
      continue;
    }
    const bullet = /^(\s*)([*+-]|\d+\.)\s+(.*)$/.exec(line);
    if (bullet) {
      ensureSpace(doc, 14);
      const depth = Math.min(Math.floor(bullet[1].replace(/\t/g, '    ').length / 4), 3);
      const indent = MARGIN + 6 + depth * 14;
      const marker = /\d+\./.test(bullet[2]) ? bullet[2] : '•';
      const top = doc.y;
      doc.font(FONT).fontSize(BODY_SIZE).fillColor(COLORS.text);
      doc.text(toPdfText(marker), indent, top, { width: 14, lineBreak: false });
      doc.y = top;
      richLine(doc, bullet[3], indent + 14, width - (indent + 14 - MARGIN), BODY_SIZE);
      continue;
    }
    ensureSpace(doc, 14);
    richLine(doc, line, MARGIN, width, BODY_SIZE);
  }
  doc.x = MARGIN;
};

const flagText = (
  flag: string | { name?: string; flag?: string; value?: string; description?: string },
): string => {
  if (typeof flag === 'string') {
    return flag;
  }
  return [flag.name ?? flag.flag, flag.value, flag.description].filter(Boolean).join(' - ');
};

const redFlagLines = (screen: TspiRedFlagScreen | null | undefined): string[] => {
  if (!screen) {
    return [];
  }
  const flags = (screen.red_flags ?? []).map(flagText);
  const critical = (screen.critical_values ?? []).map((v) => `Critical value: ${flagText(v)}`);
  const action = screen.required_action ? [`Required action: ${screen.required_action}`] : [];
  return [...flags, ...critical, ...action];
};

const alertText = (alert: string | TspiSafetyAlert): string =>
  typeof alert === 'string'
    ? alert
    : [alert.severity, alert.message ?? alert.description].filter(Boolean).join(': ');

const moduleSafety = (module: TspiModule): string =>
  [
    module.safety_outcome,
    module.safety,
    module.contraindications?.length
      ? `Contraindications: ${module.contraindications.join(', ')}`
      : '',
  ]
    .filter(Boolean)
    .join('\n');

const editTarget = (edit: TspiEdit): string =>
  edit.target ?? edit.module_code ?? edit.axis_code ?? '-';

const labStatus = (concept: string | null | undefined): string =>
  concept?.startsWith('lab:') ? 'Not recognised' : 'Used';

const statusLine = (doc: Doc, plan: TspiPlanRecord, approval: TspiApproval, viewer: TspiViewer) => {
  const approver = plan.payload.approved_by;
  let text = 'AI DRAFT – pending physician approval';
  let color = COLORS.orange;
  if (approval === 'approved') {
    text = `APPROVED by ${approver?.name ?? 'TSPI physician'} on ${formatTimestamp(approver?.at)}`;
    color = COLORS.blue;
  } else if (approval === 'rejected') {
    text = `REJECTED by ${approver?.name ?? 'TSPI physician'} on ${formatTimestamp(approver?.at)}`;
  } else if (viewer.role === 'patient') {
    text = 'UNREVIEWED AI DRAFT – Not reviewed by a TSPI doctor';
  }
  doc.font(FONT_BOLD).fontSize(11).fillColor(color);
  doc.text(toPdfText(text), MARGIN, doc.y, { width: contentWidth(doc) });
  doc.moveDown(0.5);
};

const watermarkText = (approval: TspiApproval, viewer: TspiViewer): string | undefined => {
  if (approval === 'approved') {
    return undefined;
  }
  if (approval === 'rejected') {
    return 'REJECTED – NOT FOR PATIENT USE';
  }
  return viewer.role === 'patient'
    ? 'UNREVIEWED AI DRAFT – NOT MEDICAL ADVICE'
    : 'DRAFT – NOT FOR PATIENT USE';
};

const decoratePages = (doc: Doc, watermark: string | undefined): void => {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const bottomMargin = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    if (watermark) {
      const text = toPdfText(watermark);
      doc.save();
      const cx = doc.page.width / 2;
      const cy = doc.page.height / 2;
      const span = Math.hypot(doc.page.width, doc.page.height) * 0.7;
      doc.font(FONT_BOLD).fontSize(48);
      const size = Math.min(48, (48 * span) / doc.widthOfString(text));
      doc.fontSize(size).fillColor(COLORS.watermark).fillOpacity(0.25);
      const width = doc.widthOfString(text);
      doc.rotate(-45, { origin: [cx, cy] });
      doc.text(text, cx - width / 2, cy - size / 2, { lineBreak: false });
      doc.restore();
    }
    const footerTop = doc.page.height - MARGIN - FOOTER_HEIGHT + 10;
    const width = contentWidth(doc);
    doc
      .moveTo(MARGIN, footerTop - 4)
      .lineTo(MARGIN + width, footerTop - 4)
      .lineWidth(0.5)
      .strokeColor(COLORS.rule)
      .stroke();
    doc.font(FONT).fontSize(7.5).fillColor(COLORS.muted);
    doc.text(FOOTER_TEXT, MARGIN, footerTop, { width: width - 70 });
    const pageLabel = `Page ${i - range.start + 1} of ${range.count}`;
    doc.text(pageLabel, MARGIN + width - 65, footerTop, { width: 65, align: 'right' });
    doc.page.margins.bottom = bottomMargin;
  }
};

const renderBody = (doc: Doc, plan: TspiPlanRecord, viewer: TspiViewer): TspiApproval => {
  const { payload } = plan;
  const analysis = payload.analysis ?? {};
  const approval = getApproval(plan);
  const isPatient = viewer.role === 'patient';

  statusLine(doc, plan, approval, viewer);
  if (isPatient && approval !== 'approved') {
    noticeBox(
      doc,
      [
        'UNREVIEWED AI DRAFT. Not reviewed or approved by a TSPI doctor. Not medical advice.',
        `Do not start, stop or change any medicine or supplement because of this report. Contact TSPI Digital Twin for doctor review: ${PATIENT_CONTACT_URL}`,
      ],
      COLORS.orange,
    );
  }
  const notice = payload.pilot_notice ?? payload.disclaimer;
  if (notice) {
    noticeBox(doc, [notice], COLORS.orange);
  }

  sectionTitle(doc, 'Case summary');
  const symptoms = (analysis.phenotype?.symptoms_identified ?? [])
    .map((s) => s.name)
    .filter(Boolean)
    .join(', ');
  const phenotypes = (analysis.phenotype?.phenotypes ?? [])
    .map((p) =>
      p.confidence != null
        ? `${p.phenotype_name_en} (${Math.round(p.confidence * 100)}% confidence)`
        : p.phenotype_name_en,
    )
    .filter(Boolean)
    .join('\n');
  const nss = plan.nss != null ? String(plan.nss) : '-';
  const severity = [
    analysis.severity_name,
    plan.severity_level != null ? `level ${plan.severity_level}` : '',
  ]
    .filter(Boolean)
    .join(', ');
  keyValueTable(doc, [
    ['Case code', getCaseCode(plan)],
    ['Report ID', plan.id],
    ['Generated', formatTimestamp(payload.created_by?.at)],
    ['Network Stress Score (NSS)', severity ? `${nss} (${severity})` : nss],
    ['Overall confidence', payload.nss_detail?.overall_confidence_label ?? '-'],
    ['Prakati gap', humanize(analysis.prakati_gap)],
    [
      'Nine-step position',
      analysis.nine_step_position != null ? String(analysis.nine_step_position) : '-',
    ],
    ['Symptoms identified', symptoms || '-'],
    ['Candidate phenotypes', phenotypes || '-'],
    ['Framework', payload.framework_version ?? '-'],
  ]);

  sectionTitle(doc, 'Red flags');
  const flags = redFlagLines(payload.red_flag_screen);
  if (flags.length) {
    noticeBox(doc, flags, '#C62828');
  } else {
    paragraph(doc, 'None reported by the engine.', COLORS.muted);
  }

  const alerts = [...(plan.safety_alerts ?? []), ...(payload.safety_alerts ?? [])].map(alertText);
  if (alerts.length) {
    sectionTitle(doc, 'Safety alerts');
    noticeBox(doc, alerts, '#C62828');
  }

  if (payload.report_markdown) {
    sectionTitle(doc, 'Clinical report');
    markdown(doc, payload.report_markdown);
  }

  const axes = analysis.axis_scores ?? [];
  if (axes.length) {
    sectionTitle(doc, 'Biological assessment (39-axis)');
    table(
      doc,
      [
        ['Axis', 0.24],
        ['Status', 0.17],
        ['Score', 0.08],
        ['Severity', 0.15],
        ['Evidence', 0.36],
      ],
      axes.map((axis) => [
        `${axis.axis_code ?? ''} ${axis.axis_name ?? ''}${axis.is_driver ? ' (driver)' : ''}`.trim(),
        humanize(axis.status),
        axis.score != null ? String(axis.score) : '-',
        humanize(axis.severity),
        (axis.evidence ?? []).map((e) => e.replace(/\s*~RAG\([^)]*\)/g, '')).join('\n') ||
          humanize(axis.evidence_status),
      ]),
    );
  }

  const networks = payload.networks ?? [];
  if (networks.length) {
    sectionTitle(doc, 'Networks');
    table(
      doc,
      [
        ['Network', 0.16],
        ['Name', 0.5],
        ['Primary axis', 0.14],
        ['Mapping', 0.2],
      ],
      networks.map((n) => [
        n.network_code ?? '-',
        n.name ?? '-',
        n.primary_axis ?? '-',
        humanize(n.mapping_status),
      ]),
    );
  }

  sectionTitle(doc, 'Treatment modules');
  const modules = payload.modules ?? [];
  if (modules.length) {
    table(
      doc,
      [
        ['Module', 0.27],
        ['Dose', 0.16],
        ['Role / tier', 0.12],
        ['Phase', 0.09],
        ['Target axes', 0.18],
        ['Safety', 0.18],
      ],
      modules.map((m) => [
        `${m.module_code ?? ''}\n${m.module_name ?? ''}`.trim(),
        m.dose ?? '-',
        [humanize(m.clinical_role), m.tier ? humanize(m.tier) : ''].filter(Boolean).join(' / '),
        humanize(m.phase),
        (m.target_axes ?? []).join(', '),
        moduleSafety(m) || '-',
      ]),
    );
  } else {
    paragraph(doc, 'No modules returned by the engine.', COLORS.muted);
  }

  const signals = analysis.signals ?? [];
  if (signals.length) {
    sectionTitle(doc, 'Lab and symptom usage');
    table(
      doc,
      [
        ['Result', 0.38],
        ['Interpreted as', 0.32],
        ['Evidence', 0.15],
        ['Status', 0.15],
      ],
      signals.map((s) => [
        s.source ?? '-',
        s.concept?.startsWith('lab:') ? '-' : (s.concept ?? '-'),
        humanize(s.evidence_status),
        labStatus(s.concept),
      ]),
    );
  }

  const reassess = (payload.monitoring ?? []).flatMap((m) => m.reassess_every_days ?? []);
  if (reassess.length) {
    sectionTitle(doc, 'Monitoring');
    paragraph(doc, `Reassess every ${reassess.join('–')} days.`);
  }

  const edits = payload.edits ?? [];
  if (edits.length) {
    sectionTitle(doc, 'Physician edits');
    table(
      doc,
      [
        ['Action', 0.18],
        ['Target', 0.18],
        ['Reason code', 0.2],
        ['Rationale', 0.44],
      ],
      edits.map((e) => [
        humanize(e.action),
        editTarget(e),
        e.reason_code ?? '-',
        e.rationale ?? '-',
      ]),
    );
  }

  if (payload.disclaimer && payload.disclaimer !== notice) {
    sectionTitle(doc, 'Disclaimer');
    paragraph(doc, payload.disclaimer, COLORS.muted);
  }
  return approval;
};

/** Renders a TSPI treatment plan as an A4 PDF following the TSPI report template. */
export const renderReportPdf = (plan: TspiPlanRecord, viewer: TspiViewer): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      bufferPages: true,
      margins: {
        top: HEADER_HEIGHT + 22,
        bottom: MARGIN + FOOTER_HEIGHT,
        left: MARGIN,
        right: MARGIN,
      },
      info: {
        Title: `TSPI treatment plan ${getCaseCode(plan)}`,
        Author: 'TSPI Digital Twin',
        Subject: `Report ${plan.id}`,
      },
    });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.on('pageAdded', () => drawHeaderBar(doc, plan));

    try {
      drawHeaderBar(doc, plan);
      const approval = renderBody(doc, plan, viewer);
      decoratePages(doc, watermarkText(approval, viewer));
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
